# Generated by Django 4.1.5 on 2023-01-12 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umraduo',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
