# Generated by Django 4.1.5 on 2023-01-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Safarga tayyorgarlik',
                'verbose_name_plural': 'Safarga tayyorgarlik',
            },
        ),
    ]
